name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.19.0'

      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
          # keep_files: true
          user_name: cbuschka
          user_email: cbuschka@gmail.com
          publish_branch: gh-pages
